
import { Language, TranslationMap, Product } from './types';
export const TRANSLATIONS: TranslationMap = {
  [Language.TC]: {
    home: "首頁",
    about: "關於柯洛克",
    products: "產品介紹",
    admin: "系統管理",
    my_orders: "我的訂單",
    cart: "購物車",
    login: "用戶登錄",
    logout: "安全退出",
    register: "賬號註冊",
  // 註冊與登錄界面
    titleRegister: "用戶註冊",
    titleLogin: "用戶登入",
    username: "用戶名稱",
    password: "密碼",
    email: "電子郵件地址 * (例如: example@mail.com)",
    name: "聯繫人姓名",
    phone: "聯繫電話",
    address: "收貨地址",
    processing: "正在處理...",
    btnRegister: "立即註冊",
    btnLogin: "登入系統",
    toLogin: "已有帳號？前往登入",
    toRegister: "還沒有帳號？前往註冊",

    // 驗證與錯誤提示
    alertEmpty: "請填寫必填項（用戶名、密碼及電子郵件）",
    alertEmail: "電子郵件格式不正確！",
    auth_error_invalid: "賬號或密碼錯誤，請重試",
    auth_loading: "正在驗證信息...",
    total: "總計金額",
    checkout: "去結算",
    category_treasures: "鎮店之寶",
    category_woodpulp: "木漿普通紙巾系列",
    category_dustfree: "無塵餐巾紙系列",
    category_composite: "上膠複合紙巾系列",
    category_coaster: "杯墊系列",
    category_apron: "紙圍裙系列",
    category_facial: "抽紙系列",
    category_wet: "濕紙巾系列",
    category_large_roll: "大軸卷裝系列",
    category_toilet_roll: "彩色卷裝衛生紙系列",
    category_cloak: "柯洛克品牌系列",
    category_rawmaterial: "原材料系列",
    stock: "現有庫存",
    order_status: "訂單狀態",
    placed: "已落單",
    picking: "揀貨中",
    shipped: "已發貨",
    received: "已簽收",
    tracking_no: "快遞單號",
    add_to_cart: "加入購物車",
    sub_toilet: "衛生紙系列",
    sub_hand: "抹手紙系列",
    sub_facial: "面巾紙系列",
    sub_tissue: "抽紙系列",
    sub_wet: "濕紙巾系列",
    sub_napkin: "餐巾紙系列",
    sub_none: "其他產品", // 用於沒有設置小系列的商品
    company_intro: "柯洛克牌品牌系列生活用紙，包括有：高級歐洲進口各類無塵餐巾紙、大小卷裝廁紙、盒裝抽紙、迷你小手帕、廚房紙、擦手紙、醫用、機器抹紙、紙臺布等各類生活用紙。部份產品，更經國際權威驗證機構SGS的獨立驗證，完全符合歐洲FSC驗證和國家的衛生標準GB15979-2002的要求！憑藉我們豐富經驗和專業技術，同時接受各大小商戶（如中西餐館、桑拿會所、各大小公司、團體、個人、宴會、廣告紙巾等等）產品加工服務，訂單多少都無任歡迎！相信憑藉我們的實力，定能為閣下生產出稱心如意的貨品，並保持長期的合作夥伴關係！",
    certification_title: "資質認証",
    certification_desc: "本公司產品已通過 SGS 及 FSC 國際權威認証，符合歐盟及國家衛生標準。",
    process_title: "訂貨流程",
    step1: "註冊賬號", step2: "選購商品", step3: "結算支付", step4: "工廠揀貨", step5: "送貨簽收",
    no_account: "沒有賬號？",
    has_account: "已有賬號登錄",
    update_stock: "更新庫存",
    add_product: "上架商品",
    home_title: "柯洛克品牌系列",
    home_subtitle: "一次性餐飲外賣包裝用品及生活用紙採購平台,提供專業解決方案",
    buy_now: "立即訂貨",
    case_studies: "生產車間",
    add: "選購",
    out_of_stock: "暫時缺貨",
    unit_price: "單價",
    qty: "數量",
    proceed_checkout: "確認訂單",
    confirm_pay: "確認支付",
    order_id: "訂單編號",
    admin_inventory: "商品庫存管理",
    admin_orders: "訂單狀態跟蹤",
    edit: "修改",
    save: "保存",
    cancel: "取消",
    tracking_placeholder: "輸入物流單號...",
    dispatch: "發貨",
    complete: "完成",
    acknowledge: "揀貨",
    product_name: "商品名稱",
    price: "單價",
    img_url: "封面圖片URL",
    detail_img_url: "詳情圖URL",
    factory_video: "柯洛克生產工廠實拍",
    deep_dive: "商品詳細規格",
    status_active: "銷售中",
    status_inactive: "已下架",
    toggle_status: "上架/下架",
    display_only: "僅供展示",
    factory_live: "實地拍攝",
    auth_error_empty: "請輸入賬號和密碼",
    auth_success_login: "登錄成功！歡迎回來",
    auth_success_register: "註冊成功！已為您自動登錄",
    production_details: "生產細節",
    select_pay_method: "選擇支付方式",
    not_for_sale_hint: "只有柯洛克系列產品方可下單",
    factory_desc: "柯洛克（香港）自有全自動化生產線，嚴格把控每一道工序。",
    shipping_notice: "🚚 免費送貨：港島區滿 HKD$1500 元／單；九龍．新界區滿 HKD$1000 元／單。離島及特殊區域另議。如貨值不夠，每單加收 HKD$100 元運費。",
  },
  [Language.EN]: {
    home: "Home",
    about: "About Cloak", // ⭐ 修改
    products: "Products",
    admin: "Admin",
    my_orders: "Orders",
    cart: "Cart",
    login: "Login",
    logout: "Logout",
    register: "Register",
    titleRegister: "User Registration",
    titleLogin: "User Login",
    username: "Username",
    password: "Password",
    email: "Email Address * (e.g. example@mail.com)",
    name: "Full Name",
    phone: "Phone",
    address: "Shipping Address",
    processing: "Processing...",
    btnRegister: "Register Now",
    btnLogin: "Login",
    toLogin: "Already have an account? Login",
    toRegister: "Don't have an account? Register",

    // Validation & Messages
    alertEmpty: "Please fill in all required fields (Username, Password, and Email)",
    alertEmail: "Invalid email format!",
    auth_success_register: "Registration successful! You are now logged in.",
    auth_loading: "Verifying information...",
    total: "Total",
    checkout: "Checkout",
    category_treasures: "Shop's Treasure",
    category_woodpulp: "Wood Pulp Series",
    category_dustfree: "Airlaid Paper Series",
    category_composite: "Composite Series",
    category_coaster: "Coaster Series",
    category_apron: "Paper Apron Series",
    category_facial: "Facial Tissue Series",
    category_wet: "Wet Wipes Series",
    category_large_roll: "Jumbo Roll Series",
    category_toilet_roll: "Colored Toilet Paper",
    category_cloak: "Cloak Series",
    category_rawmaterial: "Raw Materials",
    stock: "Stock",
    order_status: "Status",
    placed: "Placed",
    picking: "Picking",
    shipped: "Shipped",
    received: "Received",
    tracking_no: "Tracking No.",
    add_to_cart: "Add to Cart",
    auth_error_empty: "Please enter username and password",
    auth_error_invalid: "Invalid username or password. Please try again.",
    auth_success_login: "Login successful! Welcome back.",
    sub_toilet: "Toilet Paper",
    sub_hand: "Hand Towels",
    sub_facial: "Facial Tissues",
    sub_tissue: "Box Tissues",
    sub_wet: "Wet Wipes",
    sub_napkin: "Napkins",
    sub_none: "Others",
    company_intro: "The 'Cloak' brand series offers a wide range of daily paper products, including premium imported European airlaid napkins, jumbo and small roll toilet paper, facial tissues, mini pocket tissues, kitchen towels, hand towels, medical paper, industrial wipes, and paper tablecloths. Some of our products have been independently verified by the international authority SGS, fully complying with European FSC certification and the national hygiene standard GB15979-2002 requirements! With our extensive experience and professional expertise, we provide custom processing services for merchants of all sizes (such as Chinese and Western restaurants, saunas, corporations, groups, individuals, banquets, promotional napkins, etc.). Orders of any quantity are welcome! We are confident in our ability to produce products that meet your satisfaction and look forward to building a long-term partnership!",
    certification_title: "Certifications",
    certification_desc: "Our products have passed SGS and FSC international authoritative certifications.",
    process_title: "Ordering Steps",
    step1: "Register", step2: "Select", step3: "Checkout", step4: "Picking", step5: "Received",
    no_account: "No account?",
    has_account: "Login here",
    update_stock: "Update Stock",
    add_product: "Add Item",
    home_title: "Cloak Brand Series",
    home_subtitle: "One-stop Procurement Platform for Disposable Catering Takeaway Packaging & Household Paper Products, Offering Professional Solutions",
    buy_now: "Shop Now",
    case_studies: "Workshop",
    add: "Add",
    out_of_stock: "Out of Stock",
    unit_price: "Price",
    qty: "Qty",
    proceed_checkout: "Place Order",
    confirm_pay: "Pay Now",
    order_id: "Order ID",
    admin_inventory: "Inventory Management",
    admin_orders: "Order Processing",
    edit: "Edit",
    save: "Save",
    cancel: "Cancel",
    tracking_placeholder: "Tracking No...",
    dispatch: "Dispatch",
    complete: "Complete",
    acknowledge: "Pick",
    product_name: "Product Name",
    price: "Price",
    img_url: "Image URL",
    detail_img_url: "Detail URL",
    factory_video: "Cloak Factory Video",
    deep_dive: "Product Specs",
    status_active: "Active",
    status_inactive: "Hidden",
    toggle_status: "Show/Hide",
    display_only: "Display Only",
    factory_live: "FACTORY LIVE",
    production_details: "PRODUCTION",
    select_pay_method: "Select Payment Method",
    not_for_sale_hint: "* Ordering is available for Cloak series only",
    shipping_notice: "🚚 Free Delivery: Orders over HKD 1,500 for HongKong Island;over HKD 1,000 for Kowloon & New Territories. Delivery to outlying islands and special areas is subject to negotiation. A HKD$100 shipping fee applies to orders below the minimum amount.",
    factory_desc: "Cloak (HK) fully automated production lines with strict quality control."
  }
};
const DEFAULT_VIDEO = "https://www.w3schools.com/html/mov_bbb.mp4";
export const INITIAL_PRODUCTS: Product[] = [

];